services:
    ######################################################
    ## Redis
    ######################################################
    redis:
      image: 'redis:5.0.5'
    #   command: redis-server --requirepass redispass
    ######################################################
    ## Postgress
    ######################################################
    postgres:
        image: postgres:9.6
        environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
        ports:
          - "5432:5432"
    ######################################################
    ## Airflow Webserver
    ######################################################
    webserver:
        image: puckel-airflow-with-docker-inside:latest
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
          - LOAD_EX=n
          - EXECUTOR=Celery
          - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
        volumes:
          - ./examples/docker-example/dags:/usr/local/airflow/dags
          - ./examples/docker-example/scrapers:/home/airflow/scrapers
          - ./examples/docker-example/data:/home/airflow/data
          - ./examples/docker-example/requirements.txt:/requirements.txt
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    ######################################################
    ## Airflow Scheduler
    ######################################################
    scheduler:
      image: puckel-airflow-with-docker-inside:latest
      restart: always
      depends_on:
          - webserver
      volumes:
        - ./examples/docker-example/dags:/usr/local/airflow/dags
        - ./examples/docker-example/scrapers:/home/airflow/scrapers
        - ./examples/docker-example/data:/home/airflow/data
        - ./examples/docker-example/requirements.txt:/requirements.txt
          # Uncomment to include custom plugins
          # - ./plugins:/usr/local/airflow/plugins
      environment:
          - LOAD_EX=n
          - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
          - EXECUTOR=Celery
          # - POSTGRES_USER=airflow
          # - POSTGRES_PASSWORD=airflow
          # - POSTGRES_DB=airflow
          # - REDIS_PASSWORD=redispass
      command: scheduler
    ######################################################
    ## Airflow Worker
    ######################################################
    worker:
        image: puckel-airflow-with-docker-inside:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
          - ./examples/docker-example/dags:/usr/local/airflow/dags
          - ./examples/docker-example/scrapers:/home/airflow/scrapers
          - ./examples/docker-example/data:/home/airflow/data
          - /var/run/docker.sock:/var/run/docker.sock
          - ./examples/docker-example/requirements.txt:/requirements.txt
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
          - DOCKER_HOST=tcp://socat:2375
          - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
          - EXECUTOR=Celery
        command: worker
    ######################################################
    ## SOcket CAT
    ######################################################
    socat:
      image: bpack/socat
      command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      expose:
        - "2375"
    ######################################################
version: '3'
#networks:
#  default:
#    name: DockerOperator
